### ISSUE TITLE
Standard Input:  argument lengths differ ERROR

### ISSUE THREAD

**Issue by nikrepp** [marjoleinF/pre#11]
set.seed(42)
airq.ens <- pre(Ozone ~ ., data = airquality[complete.cases(airquality),])
calculate global importances:
importance(airq.ens)
**Error in order(baseimps$imp, decreasing = TRUE, method = "radix") : 
  argument lengths differ**

**Comment by marjoleinF** [comment]
Thanks for reporting this issue. The code does not yield an error on my system. Can you report what version of R and what OS you are running?

**Comment by nikrepp** [comment]
Hi,

thanks for quick feedback.

R-3.1.2, OS Windows 10.

**Comment by marjoleinF** [comment]
You're welcome! Upgrading to the current R version may solve the error. 

The release notes for R 3.3.0 state that 'The order() function gains a method argument for choosing between "shell" and "radix".'  The older implementation of order() likely causes the problem.
