### ISSUE TITLE
partykit dependency

### ISSUE THREAD

**Issue by RMHogervorst** [marjoleinF/pre#2]
Hi Marjolein,

Does the package really depend on partykit? It seems you copied the function, so it doesn't need it.
If you only need a package for examples then it shouldn't be in DEPENDS, but in SUGGESTS see <http://r-pkgs.had.co.nz/description.html>

**Comment by marjoleinF** [comment]
Hi Roel,
Thanks for your comment! One of the internal functions, non-exported function from the partykit package was copied. Some exported functions from the partykit package (ctree() and glmtree() ) are also used by pre, therefore partykit is in DEPENDS.
