### ISSUE TITLE
Set intercept = FALSE change dramatically the result

### ISSUE THREAD

**Issue by elier** [marjoleinF/pre#20]
When I set "intercept = FALSE", the result change dramatically. I was expecting only that the (Intercept) line disappears and result stay very similar.

**Comment by marjoleinF** [comment]
In any regression model, the estimated model will change after removing the intercept. This seems not an issue with `pre()`, but the result I would expect by passing `intercept = FALSE` to `cv.glmnet()`. Why do you want to exclude the intercept?
