### ISSUE TITLE
Suggestion: Add winsor points to the display of coef.pre

### ISSUE THREAD

**Issue by RishiSadhir** [marjoleinF/pre#3]
Currently, coef.pre returns the following columns:

1. Rule - Variable name or 'rule###'
2. Coefficient
3. Description - NA for linear terms

I propose adding the winsor points to the description column for linear terms. Perhaps something like:

`9.9625 <= age <= 100 `

**Comment by marjoleinF** [comment]
Thanks for the suggestion! This would be helpful indeed, will be implemented in future version.

**Comment by marjoleinF** [comment]
It's implemented in the coef() and importance measures now, exactly as you suggested. Looks nice, thanks!
