### ISSUE TITLE
what is the licence on this package?  GPL-2, GPL-3, MIT?  

### ISSUE THREAD

**Issue by RMHogervorst** [marjoleinF/pre#4]

**Comment by marjoleinF** [comment]
GPL-2 | GPL-3. It's stated in the DESCRIPTION file. Should I include the licence info elsewhere?

**Comment by RMHogervorst** [comment]
missed it, sorry!
You could add it to the readme as well.

**Comment by RMHogervorst** [comment]
However! You need to include the license in the package (include a LICENCE file)
https://help.github.com/articles/licensing-a-repository/

**Comment by marjoleinF** [comment]
Thanks! Will fix that!

**Comment by marjoleinF** [comment]
Thanks for pointing this out, the current version includes a LICENCE file.
